### ISSUE TITLE
TOOLTIP: Option "container" provided type "undefined" but expected type "(string|element|boolean)"

### ISSUE THREAD

**Issue by Nowi5** [lespoupeesrusses/summernote-list-of-links#2]
Hi,

the plugin does not load with the latest version 0.8.10 of summernote. See error below:

![grafik](https://user-images.githubusercontent.com/27913135/45027417-a0af3580-b041-11e8-8c11-24eb1e8f7ef0.png)

When I remove the line with "tooltip: 'List of links'," it works somehow. But bad icon positioning.

**Comment by pabois** [comment]
Hello,
i'm working with version 0.8.10 and have no problem.
Are you sure of your configuration?

**Comment by SebouChu** [comment]
Bootstrap is required for this plugin

Regards
